[package]
name = "trx_service"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
anyhow = "1.0.86"
env_logger = "0.11.5"
rust_decimal = "1.35.0"
rust_decimal_macros = "1.35.0"
log = { version = "0.4.22", features = ["kv"] }
serde = { version = "1.0.204", features = ["derive"] }
